name = "nostr-relay-worker"
main = "src/index.ts"
compatibility_date = "2024-08-21"
workers_dev = true

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "${CONFIG_KV_ID}"
preview_id = "${CONFIG_KV_PREVIEW_ID}"

[[d1_databases]]
binding = "DB"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"
