name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Lint code
        run: pnpm run lint

      - name: Type check
        run: pnpm run typecheck

      - name: Run tests
        run: pnpm run test

      - name: Build packages
        run: pnpm run build

      - name: Publish Worker
        working-directory: apps/relay-worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
        run: |
          npx wrangler deploy src/index.ts --outdir dist --minify

      - name: Output Deployment Info
        working-directory: apps/relay-worker
        run: |
          echo "Relay URL: $(npx wrangler whoami --json | jq -r '.user.name')" || true
          echo "Deployment complete."
